name: MassiveGates
version: 1.1.3
main: com.massivecraft.massivegates.MassiveGates
depend: [MassiveCore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  massivegates.action.chat: {description: assign the chat action to a gate, default: false}
  massivegates.action.close: {description: assign the close action to a gate, default: false}
  massivegates.action.cmd: {description: assign the cmd action to a gate, default: false}
  massivegates.action.fxe: {description: assign the fxe action to a gate, default: false}
  massivegates.action.fxg: {description: assign the fxg action to a gate, default: false}
  massivegates.action.msg: {description: assign the msg action to a gate, default: false}
  massivegates.action.open: {description: assign the open action to a gate, default: false}
  massivegates.action.use: {description: assign the use action to a gate, default: false}
  massivegates.action.use_forced: {description: assign the useforce action to a gate, default: false}
  massivegates.action.reqperm: {description: assign the reqperm action to a gate, default: false}
  massivegates.action.setvel: {description: assign the setvel action to a gate, default: false}
  massivegates.delete: {description: delete a gate, default: false}
  massivegates.edit: {description: edit gate shape, default: false}
  massivegates.edit.clear: {description: clear gate parts, default: false}
  massivegates.edit.flood: {description: append using floodfill, default: false}
  massivegates.edit.that: {description: edit that block, default: false}
  massivegates.exit: {description: manage gate exit, default: false}
  massivegates.exit.get: {description: get internal exit, default: false}
  massivegates.exit.here: {description: set internal exit, default: false}
  massivegates.exit.goto: {description: got internal exit, default: false}
  massivegates.exit.remove: {description: remove internal exit, default: false}
  massivegates.fx: {description: list available special fx, default: false}
  massivegates.fx.alt: {description: list available special fx, default: false}
  massivegates.fx.test: {description: info on the special effects system, default: false}
  massivegates.list: {description: list gates, default: false}
  massivegates.matc: {description: set closed material, default: false}
  massivegates.mato: {description: set open material, default: false}
  massivegates.name: {description: manage gate name, default: false}
  massivegates.name.get: {description: get gate name, default: false}
  massivegates.name.set: {description: set gate name, default: false}
  massivegates.new: {description: create new gates, default: false}
  massivegates.open: {description:  manage gate open/closed state, default: false}
  massivegates.open.get: {description: get the open-state, default: false}
  massivegates.open.set: {description: set the open-state, default: false}
  massivegates.see: {description: visualise the gate, default: false}
  massivegates.select: {description: select a gate, default: false}
  massivegates.simple.create: {description: create simple gates, default: false}
  massivegates.simple.destroy: {description: destroy simple gates, default: false}
  massivegates.simple.use: {description: use simple gates, default: false}
  massivegates.target: {description: manage gate target, default: false }
  massivegates.target.get: {description: get current target, default: false}
  massivegates.target.gate: {description: set target to a gate, default: false}
  massivegates.target.here: {description: set target where you stand, default: false}
  massivegates.target.rubberserver: {description: target rubberband server, default: false}
  massivegates.ta: {description: manage gate trigger-actions, default: false}
  massivegates.ta.add: {description: add action, default: false}
  massivegates.ta.alt: {description: list triggers or action, default: false}
  massivegates.ta.del: {description: delete action, default: false}
  massivegates.ta.list: {description: list current trigger-action, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  massivegates.*:
    children:
      massivegates.simple.*: true
      massivegates.delete: true
      massivegates.edit.*: true
      massivegates.exit.*: true
      massivegates.fx.*: true
      massivegates.list: true
      massivegates.matc: true
      massivegates.mato: true
      massivegates.name.*: true
      massivegates.new: true
      massivegates.open.*: true
      massivegates.see: true
      massivegates.select: true
      massivegates.target.*: true
      massivegates.ta.*: true
      massivegates.action.*: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massivegates.simple.*:
    children:
      massivegates.simple.create: true
      massivegates.simple.destroy: true
      massivegates.simple.use: true
  massivegates.edit.*:
    children:
      massivegates.edit: true
      massivegates.edit.clear: true
      massivegates.edit.flood: true
      massivegates.edit.that: true
  massivegates.exit.*:
    children:
      massivegates.exit: true
      massivegates.exit.get: true
      massivegates.exit.here: true
      massivegates.exit.goto: true
      massivegates.exit.remove: true
  massivegates.fx.*:
    children:
      massivegates.fx: true
      massivegates.fx.alt: true
      massivegates.fx.test: true
  massivegates.name.*:
    children:
      massivegates.name: true
      massivegates.name.get: true
      massivegates.name.set: true
      massivegates.name.remove: true
  massivegates.open.*:
    children:
      massivegates.open: true
      massivegates.open.get: true
      massivegates.open.set: true
  massivegates.target.*:
    children:
      massivegates.target: true
      massivegates.target.get: true
      massivegates.target.set: true
      massivegates.target.here: true
      massivegates.target.gate: true
      massivegates.target.rubberserver: true
      massivegates.target.goto: true
      massivegates.target.remove: true
  massivegates.ta.*:
    children:
      massivegates.ta: true
      massivegates.ta.add: true
      massivegates.ta.alt: true
      massivegates.ta.del: true
      massivegates.ta.list: true
  massivegates.action.*:
    children:
      massivegates.action.chat: true
      massivegates.action.close: true
      massivegates.action.cmd: true
      massivegates.action.fxe: true
      massivegates.action.fxg: true
      massivegates.action.msg: true
      massivegates.action.open: true
      massivegates.action.use: true
      massivegates.action.use_forced: true
      massivegates.action.reqperm: true
      massivegates.action.setvel: true
      