name: massivegates
version: 1.1.3
main: com.massivecraft.massivegates.P
depend: [mcore4]
permissions:
  massivegates.*:
    children:
      massivegates.simple.*: true
      massivegates.delete: true
      massivegates.edit.*: true
      massivegates.exit.*: true
      massivegates.fx.*: true
      massivegates.list: true
      massivegates.matc: true
      massivegates.mato: true
      massivegates.name.*: true
      massivegates.new: true
      massivegates.open.*: true
      massivegates.see: true
      massivegates.select: true
      massivegates.target.*: true
      massivegates.ta.*: true
      massivegates.action.*: true
  massivegates.simple.*:
    children:
      massivegates.simple.create: true
      massivegates.simple.destroy: true
      massivegates.simple.use: true
  massivegates.simple.create:
    default: false
    description: create simple gates
  massivegates.simple.destroy:
    default: false
    description: destroy simple gates
  massivegates.simple.use:
    default: false
    description: use simple gates
  massivegates.delete:
    default: false
    description: delete a gate
  massivegates.edit.*:
    children:
      massivegates.edit.clear: true
      massivegates.edit.flood: true
      massivegates.edit.that: true
  massivegates.edit.clear:
    default: false
    description: clear gate parts
  massivegates.edit.flood:
    default: false
    description: append using floodfill
  massivegates.edit.that:
    default: false
    description: sniper edit
  massivegates.exit.*:
    children:
      massivegates.exit.get: true
      massivegates.exit.here: true
      massivegates.exit.goto: true
      massivegates.exit.remove: true
  massivegates.exit.get:
    default: false
    description: get internal exit
  massivegates.exit.here:
    default: false
    description: set internal exit
  massivegates.exit.goto:
    default: false
    description: goto internal exit
  massivegates.exit.remove:
    default: false
    description: remove internal exit
  massivegates.fx.*:
    children:
      massivegates.fx.alt: true
      massivegates.fx.test: true
  massivegates.fx.alt:
    default: false
    description: list available special fx
  massivegates.fx.test:
    default: false
    description: test special fx
  massivegates.list:
    default: false
    description: list gates
  massivegates.matc:
    default: false
    description: set closed material
  massivegates.mato:
    default: false
    description: set open material
  massivegates.name.*:
    children:
      massivegates.name.get: true
      massivegates.name.set: true
      massivegates.name.remove: true
  massivegates.name.get:
    default: false
    description: get gate name
  massivegates.name.set:
    default: false
    description: set gate name
  massivegates.name.remove:
    default: false
    description: remove gate name
  massivegates.new:
    default: false
    description: create new gate
  massivegates.open.*:
    children:
      massivegates.open.get: true
      massivegates.open.set: true
  massivegates.open.get:
    default: false
    description: get the open-state
  massivegates.open.set:
    default: false
    description: set the open-state
  massivegates.see:
    default: false
    description: visualise the gate
  massivegates.select:
    default: false
    description: select a gate
  massivegates.target.*:
    children:
      massivegates.target.get: true
      massivegates.target.set: true
      massivegates.target.here: true
      massivegates.target.rubberserver: true
      massivegates.target.goto: true
      massivegates.target.remove: true
  massivegates.target.get:
    default: false
    description: get current target
  massivegates.target.gate:
    default: false
    description: set target to a gate
  massivegates.target.here:
    default: false
    description: set target where you stand
  massivegates.target.rubberserver:
    default: false
    description: target rubberband server
  massivegates.target.goto:
    default: false
    description: goto current target
  massivegates.target.remove:
    default: false
    description: remove current target
  massivegates.ta.*:
    children:
      massivegates.ta.add: true
      massivegates.ta.alt: true
      massivegates.ta.del: true
      massivegates.ta.list: true
  massivegates.ta.add:
    default: false
    description: add action
  massivegates.ta.alt:
    default: false
    description: list triggers or actions
  massivegates.ta.del:
    default: false
    description: delete action
  massivegates.ta.list:
    default: false
    description: list current trigger-actions
  massivegates.action.*:
    children:
      massivegates.action.mgcore_chat: true
      massivegates.action.mgcore_close: true
      massivegates.action.mgcore_cmd: true
      massivegates.action.mgcore_fxe: true
      massivegates.action.mgcore_fxg: true
      massivegates.action.mgcore_msg: true
      massivegates.action.mgcore_open: true
      massivegates.action.mgcore_use: true
      massivegates.action.mgcore_use_forced: true
  massivegates.action.mgcore_chat:
    default: false
    description: assign the chat action to a gate
  massivegates.action.mgcore_close:
    default: false
    description: assign the close action to a gate
  massivegates.action.mgcore_cmd:
    default: false
    description: assign the cmd action to a gate
  massivegates.action.mgcore_fxe:
    default: false
    description: assign the fxe action to a gate
  massivegates.action.mgcore_fxg:
    default: false
    description: assign the fxg action to a gate
  massivegates.action.mgcore_msg:
    default: false
    description: assign the msg action to a gate
  massivegates.action.mgcore_open:
    default: false
    description: assign the open action to a gate
  massivegates.action.mgcore_use:
    default: false
    description: assign the use action to a gate
  massivegates.action.mgcore_use_forced:
    default: false
    description: assign the useforced action to a gate